### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by Der5820** [surmon-china/vue-codemirror#198]
### Describe the bug

When I scroll down the codemirror , the textarea will turn black and console will show an error  "Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')".

codemirror.js:4239 Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')
    at rm (codemirror.js:4239:23)
    at patchDisplay (codemirror.js:4257:46)
    at updateDisplayIfNeeded (codemirror.js:4161:5)
    at endOperation_W1 (codemirror.js:3869:42)
    at endOperations (codemirror.js:3846:9)
    at codemirror.js:3835:7
    at finishOperation (codemirror.js:2063:7)
    at endOperation (codemirror.js:3832:15)
    at runInOp (codemirror.js:3961:15)
    at CodeMirror.operation (codemirror.js:8668:37)

![image](https://github.com/surmon-china/vue-codemirror/assets/12471077/3aa4754f-90a2-4896-9c15-69aabb305c60)

### Reproduction

not

### System Info

```shell
mac 
"vue-codemirror": "4.0.6"
chrome
```

### Used Package Manager

npm

### Validations

- [X] Read the the documentation in detail.
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a GitHub Discussion or join our [Discord Chat Server](https://discord.surmon.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Exchar** [comment]
you can add scroll method and use instance.refresh to resolve it :)
first:
`@scroll="handleScroll"`

then
`handleScroll(instance){
instance.refresh();
}`

i just test,its perfect
